//! `JsonSerializer.Serialize(example, jsonOptions)`가 만든 도움말 예제 JSON. .NET 출력(`tests/parity/baseline/cli-run/help.json`) 그대로다.

/// `AnalyticsConfig`
pub(super) const PUT_BUCKET_ANALYTICS_EXAMPLE: &[&str] = &[
    "{",
    "  \"Id\": \"analytics1\",",
    "  \"Filter\": {",
    "    \"Prefix\": \"prefix1\",",
    "    \"Tag\": [",
    "      {",
    "        \"Key\": \"key1\",",
    "        \"Value\": \"value1\"",
    "      }",
    "    ]",
    "  },",
    "  \"Destination\": null",
    "}",
];

/// `CORSConfig`
pub(super) const PUT_BUCKET_CORS_EXAMPLE: &[&str] = &[
    "{",
    "  \"Rules\": [",
    "    {",
    "      \"AllowedHeaders\": null,",
    "      \"AllowedMethods\": [",
    "        \"GET\",",
    "        \"PUT\"",
    "      ],",
    "      \"AllowedOrigins\": [",
    "        \"*.get\",",
    "        \"*.put\"",
    "      ],",
    "      \"ExposeHeaders\": null,",
    "      \"Id\": null,",
    "      \"MaxAgeSeconds\": null",
    "    }",
    "  ]",
    "}",
];

/// `SSEConfig`
pub(super) const PUT_BUCKET_ENCRYPTION_EXAMPLE: &[&str] = &[
    "{",
    "  \"ServerSideEncryptionRules\": [",
    "    {",
    "      \"BlockedEncryptionTypes\": null,",
    "      \"BucketKeyEnabled\": null,",
    "      \"ServerSideEncryptionByDefault\": {",
    "        \"ServerSideEncryptionAlgorithm\": {",
    "          \"Value\": \"AES256\"",
    "        },",
    "        \"ServerSideEncryptionKeyManagementServiceKeyId\": null",
    "      }",
    "    }",
    "  ]",
    "}",
];

/// `InventoryConfig`
pub(super) const PUT_BUCKET_INVENTORY_EXAMPLE: &[&str] = &[
    "{",
    "  \"IsEnabled\": true,",
    "  \"Id\": \"inventory1\",",
    "  \"Destination\": {",
    "    \"AccountId\": null,",
    "    \"BucketName\": \"arn:aws:s3:::test1\",",
    "    \"Format\": \"CSV\",",
    "    \"Prefix\": \"test1/\",",
    "    \"Encryption\": null",
    "  },",
    "  \"Schedule\": \"Daily\",",
    "  \"InventoryOptionalFields\": [",
    "    \"Size\",",
    "    \"LastModifiedDate\"",
    "  ]",
    "}",
];

/// `Logging`
pub(super) const PUT_BUCKET_LOGGING_EXAMPLE: &[&str] = &[
    "{",
    "  \"Grants\": null,",
    "  \"TargetBucketName\": \"BucketName\",",
    "  \"TargetObjectKeyFormat\": null,",
    "  \"TargetPrefix\": \"logs\"",
    "}",
];

/// `MetricsConfig`
pub(super) const PUT_BUCKET_METRICS_EXAMPLE: &[&str] = &[
    "{",
    "  \"Id\": \"metrics1\",",
    "  \"Filter\": {",
    "    \"Prefix\": \"prefix1\",",
    "    \"Tag\": [",
    "      {",
    "        \"Key\": \"key1\",",
    "        \"Value\": \"value1\"",
    "      }",
    "    ]",
    "  }",
    "}",
];

/// `Notification`
pub(super) const PUT_BUCKET_NOTIFICATION_EXAMPLE: &[&str] = &[
    "{",
    "  \"TopicConfigurations\": [",
    "    {",
    "      \"Id\": \"id\",",
    "      \"Topic\": \"arn:aws:string\",",
    "      \"Events\": [",
    "        \"s3:ObjectCreated:*\",",
    "        \"s3:Replication:OperationReplicatedAfterThreshold\",",
    "        \"s3:Replication:OperationMissedThreshold\",",
    "        \"s3:Replication:OperationNotTracked\",",
    "        \"s3:Replication:OperationFailedReplication\",",
    "        \"s3:Replication:*\",",
    "        \"s3:ObjectRestore:Completed\",",
    "        \"s3:ObjectRestore:*\",",
    "        \"s3:ObjectRestore:Post\",",
    "        \"s3:ObjectRemoved:DeleteMarkerCreated\",",
    "        \"s3:ObjectRemoved:Delete\",",
    "        \"s3:ObjectRemoved:*\",",
    "        \"s3:ObjectCreated:CompleteMultipartUpload\",",
    "        \"s3:ObjectCreated:Copy\",",
    "        \"s3:ObjectCreated:Post\",",
    "        \"s3:ObjectCreated:Put\",",
    "        \"s3:ReducedRedundancyLostObject\"",
    "      ],",
    "      \"Filter\": {",
    "        \"S3KeyFilter\": {",
    "          \"FilterRules\": [",
    "            {",
    "              \"Name\": \"\\u0022prefix\\u0022|\\u0022suffix\\u0022\",",
    "              \"Value\": \"value\"",
    "            }",
    "          ]",
    "        }",
    "      }",
    "    }",
    "  ],",
    "  \"QueueConfigurations\": [",
    "    {",
    "      \"Id\": \"id\",",
    "      \"Queue\": \"arn:aws:string\",",
    "      \"Events\": [",
    "        \"s3:ObjectCreated:*\",",
    "        \"s3:Replication:OperationReplicatedAfterThreshold\",",
    "        \"s3:Replication:OperationMissedThreshold\",",
    "        \"s3:Replication:OperationNotTracked\",",
    "        \"s3:Replication:OperationFailedReplication\",",
    "        \"s3:Replication:*\",",
    "        \"s3:ObjectRestore:Completed\",",
    "        \"s3:ObjectRestore:*\",",
    "        \"s3:ObjectRestore:Post\",",
    "        \"s3:ObjectRemoved:DeleteMarkerCreated\",",
    "        \"s3:ObjectRemoved:Delete\",",
    "        \"s3:ObjectRemoved:*\",",
    "        \"s3:ObjectCreated:CompleteMultipartUpload\",",
    "        \"s3:ObjectCreated:Copy\",",
    "        \"s3:ObjectCreated:Post\",",
    "        \"s3:ObjectCreated:Put\",",
    "        \"s3:ReducedRedundancyLostObject\"",
    "      ],",
    "      \"Filter\": {",
    "        \"S3KeyFilter\": {",
    "          \"FilterRules\": [",
    "            {",
    "              \"Name\": \"\\u0022prefix\\u0022|\\u0022suffix\\u0022\",",
    "              \"Value\": \"string\"",
    "            }",
    "          ]",
    "        }",
    "      }",
    "    }",
    "  ],",
    "  \"LambdaFunctionConfigurations\": [",
    "    {",
    "      \"Id\": \"string\",",
    "      \"FunctionArn\": \"arn:aws:string\",",
    "      \"Events\": [",
    "        \"s3:ObjectCreated:*\",",
    "        \"s3:Replication:OperationReplicatedAfterThreshold\",",
    "        \"s3:Replication:OperationMissedThreshold\",",
    "        \"s3:Replication:OperationNotTracked\",",
    "        \"s3:Replication:OperationFailedReplication\",",
    "        \"s3:Replication:*\",",
    "        \"s3:ObjectRestore:Completed\",",
    "        \"s3:ObjectRestore:*\",",
    "        \"s3:ObjectRestore:Post\",",
    "        \"s3:ObjectRemoved:DeleteMarkerCreated\",",
    "        \"s3:ObjectRemoved:Delete\",",
    "        \"s3:ObjectRemoved:*\",",
    "        \"s3:ObjectCreated:CompleteMultipartUpload\",",
    "        \"s3:ObjectCreated:Copy\",",
    "        \"s3:ObjectCreated:Post\",",
    "        \"s3:ObjectCreated:Put\",",
    "        \"s3:ReducedRedundancyLostObject\"",
    "      ],",
    "      \"Filter\": {",
    "        \"S3KeyFilter\": {",
    "          \"FilterRules\": [",
    "            {",
    "              \"Name\": \"\\u0022prefix\\u0022|\\u0022suffix\\u0022\",",
    "              \"Value\": \"string\"",
    "            }",
    "          ]",
    "        }",
    "      }",
    "    }",
    "  ],",
    "  \"ExpectedBucketOwner\": null",
    "}",
];

/// `Website`
pub(super) const PUT_BUCKET_WEBSITE_EXAMPLE: &[&str] = &[
    "{",
    "  \"ErrorDocument\": \"400\",",
    "  \"IndexDocumentSuffix\": \"a\",",
    "  \"RedirectAllRequestsTo\": null,",
    "  \"RoutingRules\": null",
    "}",
];
